apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sample
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 9376
          protocol: TCP
